services:
  qna-fastapi:
    build: .
    container_name: qna_fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
      - ./vector_db_stores:/app/vector_db_stores
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=sqlite:////./app/data/sql_app.db
      - PERSIST_DIR=/app/vector_db_stores/faiss_store
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    environment:
      - PYTHONWARNINGS=ignore
    ports:
      - "6380:6379"

volumes:
  sqlite_data:
